# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af2e298cdfeabdb6935209f0eca201a17f3ccee730b4894b7c78e005dc299e397382f66c22af7a2db886eeff7e10d547f3eab55ea9ee64e0d9d22e6fc4243b75

test:
  secret_key_base: e842f6deac668dce06dc8932e3637a25168b577da767cf0f97a9ac6b7d23f4dffa8c1963d3e55c974b93f8f9b6fd7042b155fc26c15701dd67dfa8a2f08e6993

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
